dist: trusty

language: node_js

node_js:
  - '12.16.3'

cache:
  directories:
    - '$HOME/.npm'
    - coverage
    - lib

services:
  - docker

before_install:
  - docker-compose pull
  - docker-compose up
  - docker-compose --version
  - docker ps

script: echo "Running tests against $(node -v) ..."

branches:
  only:
    - master
    - dev

addons:
  sonarcloud:
    organization: 'katesclau'
    token:
      secure: $SONAR_TOKEN

jobs:
  include:
    - stage: test
      name: 'Integration tests'
      script: yarn test
    - stage: codecoverage
      name: 'Sonarqube gateway'
      script:
        - git fetch --no-tags https://github.com/katesclau/event-store-node.git +refs/heads/master:refs/remotes/origin/master
        - sonar-scanner
        - npx codecov
    - stage: build
      name: 'Build lib'
      script: yarn build
    - stage: npm release
      node_js: '12.16.3'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: 'katesclau@gmail.com'
        api_key: $NPM_API_KEY
        gem: katesclau/event-store-node
        on:
          branch: master

stages:
  - test
  - codecoverage
  - name: build
    if: branch = master
  - name: npm release
    if: branch = master
