dist: trusty

language: node_js

node_js:
  - '12.16.3'

cache:
  directories:
    - '$HOME/.npm'
    - coverage
    - lib

script: echo "Running tests against $(node -v) ..."

branches:
  only:
    - master
    - dev

jobs:
  include:
    - stage: build
      name: 'Build lib'
      script: yarn build
    - stage: npm release
      node_js: '12.16.3'
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: 'katesclau@gmail.com'
        api_key: ${NPM_API_KEY}
        gem: katesclau/event-store-node
        on:
          branch: master

stages:
  - name: build
    if: branch = master
  - name: npm release
    if: branch = master
